# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: 50f45df7df6c
Revises: 624f4f69b373
Create Date: 2026-07-14 15:00:59.741150

"""

# revision identifiers, used by Alembic.
revision = '50f45df7df6c'
down_revision = '624f4f69b373'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dashboards_version', 'is_managed_externally',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('slices_version', 'is_managed_externally',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('sql_metrics_version', 'metric_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               autoincrement=False)
    op.alter_column('sql_metrics_version', 'expression',
               existing_type=sa.TEXT(),
               nullable=True,
               autoincrement=False)
    op.alter_column('table_columns_version', 'column_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               autoincrement=False)
    op.alter_column('tables_version', 'is_managed_externally',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('tables_version', 'table_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True,
               autoincrement=False)
    op.alter_column('tables_version', 'database_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables_version', 'database_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('tables_version', 'table_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False,
               autoincrement=False)
    op.alter_column('tables_version', 'is_managed_externally',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('table_columns_version', 'column_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               autoincrement=False)
    op.alter_column('sql_metrics_version', 'expression',
               existing_type=sa.TEXT(),
               nullable=False,
               autoincrement=False)
    op.alter_column('sql_metrics_version', 'metric_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               autoincrement=False)
    op.alter_column('slices_version', 'is_managed_externally',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('dashboards_version', 'is_managed_externally',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
