# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: 624f4f69b373
Revises: None
Create Date: 2026-07-14 14:58:21.914182

"""

# revision identifiers, used by Alembic.
revision = '624f4f69b373'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

import superset

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_slices_version',
    sa.Column('dashboard_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('slice_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('dashboard_id', 'slice_id', 'transaction_id')
    )
    op.create_index(op.f('ix_dashboard_slices_version_end_transaction_id'), 'dashboard_slices_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_dashboard_slices_version_operation_type'), 'dashboard_slices_version', ['operation_type'], unique=False)
    op.create_index('ix_dashboard_slices_version_pk_transaction_id', 'dashboard_slices_version', ['dashboard_id', 'slice_id', sa.literal_column('transaction_id DESC')], unique=False)
    op.create_index('ix_dashboard_slices_version_pk_validity', 'dashboard_slices_version', ['dashboard_id', 'slice_id', 'transaction_id', 'end_transaction_id'], unique=False)
    op.create_index(op.f('ix_dashboard_slices_version_transaction_id'), 'dashboard_slices_version', ['transaction_id'], unique=False)
    op.create_table('dashboards_version',
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('dashboard_title', sa.String(length=500), autoincrement=False, nullable=True),
    sa.Column('position_json', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('css', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), autoincrement=False, nullable=True),
    sa.Column('theme_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('certified_by', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('certification_details', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('json_metadata', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), autoincrement=False, nullable=True),
    sa.Column('slug', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('published', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('is_managed_externally', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('external_url', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_dashboards_version_end_transaction_id'), 'dashboards_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_dashboards_version_operation_type'), 'dashboards_version', ['operation_type'], unique=False)
    op.create_index('ix_dashboards_version_pk_transaction_id', 'dashboards_version', ['id', sa.literal_column('transaction_id DESC')], unique=False)
    op.create_index('ix_dashboards_version_pk_validity', 'dashboards_version', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
    op.create_index(op.f('ix_dashboards_version_transaction_id'), 'dashboards_version', ['transaction_id'], unique=False)
    op.create_table('slices_version',
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('slice_name', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('datasource_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('datasource_type', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('datasource_name', sa.String(length=2000), autoincrement=False, nullable=True),
    sa.Column('viz_type', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('params', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('cache_timeout', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('certified_by', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('certification_details', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('is_managed_externally', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('external_url', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_slices_version_end_transaction_id'), 'slices_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_slices_version_operation_type'), 'slices_version', ['operation_type'], unique=False)
    op.create_index('ix_slices_version_pk_transaction_id', 'slices_version', ['id', sa.literal_column('transaction_id DESC')], unique=False)
    op.create_index('ix_slices_version_pk_validity', 'slices_version', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
    op.create_index(op.f('ix_slices_version_transaction_id'), 'slices_version', ['transaction_id'], unique=False)
    op.create_table('sql_metrics_version',
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('metric_name', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('verbose_name', sa.String(length=1024), autoincrement=False, nullable=True),
    sa.Column('metric_type', sa.String(length=32), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), autoincrement=False, nullable=True),
    sa.Column('d3format', sa.String(length=128), autoincrement=False, nullable=True),
    sa.Column('currency', superset.models.sql_types.base.CurrencyType(), autoincrement=False, nullable=True),
    sa.Column('warning_text', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('table_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('expression', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), autoincrement=False, nullable=False),
    sa.Column('extra', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_sql_metrics_version_end_transaction_id'), 'sql_metrics_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_sql_metrics_version_operation_type'), 'sql_metrics_version', ['operation_type'], unique=False)
    op.create_index('ix_sql_metrics_version_pk_transaction_id', 'sql_metrics_version', ['id', sa.literal_column('transaction_id DESC')], unique=False)
    op.create_index('ix_sql_metrics_version_pk_validity', 'sql_metrics_version', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
    op.create_index(op.f('ix_sql_metrics_version_transaction_id'), 'sql_metrics_version', ['transaction_id'], unique=False)
    op.create_table('table_columns_version',
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('column_name', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('verbose_name', sa.String(length=1024), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('type', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('advanced_data_type', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('groupby', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('filterable', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), autoincrement=False, nullable=True),
    sa.Column('table_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('is_dttm', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('expression', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), autoincrement=False, nullable=True),
    sa.Column('python_date_format', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('datetime_format', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('extra', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_table_columns_version_end_transaction_id'), 'table_columns_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_table_columns_version_operation_type'), 'table_columns_version', ['operation_type'], unique=False)
    op.create_index('ix_table_columns_version_pk_transaction_id', 'table_columns_version', ['id', sa.literal_column('transaction_id DESC')], unique=False)
    op.create_index('ix_table_columns_version_pk_validity', 'table_columns_version', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
    op.create_index(op.f('ix_table_columns_version_transaction_id'), 'table_columns_version', ['transaction_id'], unique=False)
    op.create_table('tables_version',
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('default_endpoint', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('filter_select_enabled', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('offset', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('cache_timeout', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('params', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('is_managed_externally', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('external_url', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.String(length=250), autoincrement=False, nullable=False),
    sa.Column('main_dttm_col', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('currency_code_column', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('database_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('fetch_values_predicate', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('schema', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('catalog', sa.String(length=256), autoincrement=False, nullable=True),
    sa.Column('sql', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), autoincrement=False, nullable=True),
    sa.Column('is_sqllab_view', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('template_params', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('extra', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('normalize_columns', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('always_filter_main_dttm', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('folders', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_tables_version_end_transaction_id'), 'tables_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_tables_version_operation_type'), 'tables_version', ['operation_type'], unique=False)
    op.create_index('ix_tables_version_pk_transaction_id', 'tables_version', ['id', sa.literal_column('transaction_id DESC')], unique=False)
    op.create_index('ix_tables_version_pk_validity', 'tables_version', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
    op.create_index(op.f('ix_tables_version_transaction_id'), 'tables_version', ['transaction_id'], unique=False)
    op.create_table('version_transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_kind', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('secondary_label', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('extra_search', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['ab_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id'),
    sa.UniqueConstraint('role_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_subjects_extra_search', 'subjects', ['extra_search'], unique=False)
    op.create_index('ix_subjects_label', 'subjects', ['label'], unique=False)
    op.create_table('chart_editors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['slices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'chart_id')
    )
    op.create_table('chart_viewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['slices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'chart_id')
    )
    op.create_table('rls_filter_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('rls_filter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rls_filter_id'], ['row_level_security_filters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_editors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'dashboard_id')
    )
    op.create_table('dashboard_viewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'dashboard_id')
    )
    op.create_table('sqlatable_editors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'table_id')
    )
    op.create_table('report_schedule_editors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('report_schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_schedule_id'], ['report_schedule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'report_schedule_id')
    )
    op.drop_table('dashboard_roles')
    op.drop_table('rls_filter_roles')
    op.drop_table('dashboard_user')
    op.drop_table('slice_user')
    op.drop_table('report_schedule_user')
    op.drop_table('sqlatable_user')
    op.alter_column('dashboard_slices', 'dashboard_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dashboard_slices', 'slice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('uq_dashboard_slice', 'dashboard_slices', type_='unique')
    op.drop_column('dashboard_slices', 'id')
    op.add_column('dashboards', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_constraint('idx_unique_slug', 'dashboards', type_='unique')
    op.create_index(op.f('ix_dashboards_deleted_at'), 'dashboards', ['deleted_at'], unique=False)
    op.alter_column('rls_filter_tables', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rls_filter_tables', 'rls_filter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('rls_filter_tables', 'id')
    op.add_column('slices', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_slices_deleted_at'), 'slices', ['deleted_at'], unique=False)
    op.add_column('tables', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tables_deleted_at'), 'tables', ['deleted_at'], unique=False)
    op.drop_constraint('tagged_object_object_id_fkey2', 'tagged_object', type_='foreignkey')
    op.drop_constraint('tagged_object_object_id_fkey', 'tagged_object', type_='foreignkey')
    op.drop_constraint('tagged_object_object_id_fkey1', 'tagged_object', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tagged_object_object_id_fkey1', 'tagged_object', 'slices', ['object_id'], ['id'])
    op.create_foreign_key('tagged_object_object_id_fkey', 'tagged_object', 'saved_query', ['object_id'], ['id'])
    op.create_foreign_key('tagged_object_object_id_fkey2', 'tagged_object', 'dashboards', ['object_id'], ['id'])
    op.drop_index(op.f('ix_tables_deleted_at'), table_name='tables')
    op.drop_column('tables', 'deleted_at')
    op.drop_index(op.f('ix_slices_deleted_at'), table_name='slices')
    op.drop_column('slices', 'deleted_at')
    op.add_column('rls_filter_tables', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('rls_filter_tables', 'rls_filter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rls_filter_tables', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_dashboards_deleted_at'), table_name='dashboards')
    op.create_unique_constraint('idx_unique_slug', 'dashboards', ['slug'])
    op.drop_column('dashboards', 'deleted_at')
    op.add_column('dashboard_slices', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('uq_dashboard_slice', 'dashboard_slices', ['dashboard_id', 'slice_id'])
    op.alter_column('dashboard_slices', 'slice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dashboard_slices', 'dashboard_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('sqlatable_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='fk_sqlatable_user_table_id_tables', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], name='fk_sqlatable_user_user_id_ab_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sqlatable_user_pkey')
    )
    op.create_table('report_schedule_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['report_schedule_id'], ['report_schedule.id'], name='fk_report_schedule_user_report_schedule_id_report_schedule', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], name='fk_report_schedule_user_user_id_ab_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='report_schedule_user_pkey'),
    sa.UniqueConstraint('user_id', 'report_schedule_id', name='report_schedule_user_user_id_report_schedule_id_key')
    )
    op.create_table('slice_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['slice_id'], ['slices.id'], name='fk_slice_user_slice_id_slices', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], name='fk_slice_user_user_id_ab_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='slice_user_pkey')
    )
    op.create_table('dashboard_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dashboard_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name='fk_dashboard_user_dashboard_id_dashboards', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], name='fk_dashboard_user_user_id_ab_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dashboard_user_pkey')
    )
    op.create_table('rls_filter_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rls_filter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rls_filter_id'], ['row_level_security_filters.id'], name='rls_filter_roles_rls_filter_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], name='rls_filter_roles_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rls_filter_roles_pkey')
    )
    op.create_table('dashboard_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dashboard_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name='fk_dashboard_roles_dashboard_id_dashboards', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], name='fk_dashboard_roles_role_id_ab_role', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dashboard_roles_pkey')
    )
    op.drop_table('report_schedule_editors')
    op.drop_table('sqlatable_editors')
    op.drop_table('dashboard_viewers')
    op.drop_table('dashboard_editors')
    op.drop_table('rls_filter_subjects')
    op.drop_table('chart_viewers')
    op.drop_table('chart_editors')
    op.drop_index('ix_subjects_label', table_name='subjects')
    op.drop_index('ix_subjects_extra_search', table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('version_transaction')
    op.drop_index(op.f('ix_tables_version_transaction_id'), table_name='tables_version')
    op.drop_index('ix_tables_version_pk_validity', table_name='tables_version')
    op.drop_index('ix_tables_version_pk_transaction_id', table_name='tables_version')
    op.drop_index(op.f('ix_tables_version_operation_type'), table_name='tables_version')
    op.drop_index(op.f('ix_tables_version_end_transaction_id'), table_name='tables_version')
    op.drop_table('tables_version')
    op.drop_index(op.f('ix_table_columns_version_transaction_id'), table_name='table_columns_version')
    op.drop_index('ix_table_columns_version_pk_validity', table_name='table_columns_version')
    op.drop_index('ix_table_columns_version_pk_transaction_id', table_name='table_columns_version')
    op.drop_index(op.f('ix_table_columns_version_operation_type'), table_name='table_columns_version')
    op.drop_index(op.f('ix_table_columns_version_end_transaction_id'), table_name='table_columns_version')
    op.drop_table('table_columns_version')
    op.drop_index(op.f('ix_sql_metrics_version_transaction_id'), table_name='sql_metrics_version')
    op.drop_index('ix_sql_metrics_version_pk_validity', table_name='sql_metrics_version')
    op.drop_index('ix_sql_metrics_version_pk_transaction_id', table_name='sql_metrics_version')
    op.drop_index(op.f('ix_sql_metrics_version_operation_type'), table_name='sql_metrics_version')
    op.drop_index(op.f('ix_sql_metrics_version_end_transaction_id'), table_name='sql_metrics_version')
    op.drop_table('sql_metrics_version')
    op.drop_index(op.f('ix_slices_version_transaction_id'), table_name='slices_version')
    op.drop_index('ix_slices_version_pk_validity', table_name='slices_version')
    op.drop_index('ix_slices_version_pk_transaction_id', table_name='slices_version')
    op.drop_index(op.f('ix_slices_version_operation_type'), table_name='slices_version')
    op.drop_index(op.f('ix_slices_version_end_transaction_id'), table_name='slices_version')
    op.drop_table('slices_version')
    op.drop_index(op.f('ix_dashboards_version_transaction_id'), table_name='dashboards_version')
    op.drop_index('ix_dashboards_version_pk_validity', table_name='dashboards_version')
    op.drop_index('ix_dashboards_version_pk_transaction_id', table_name='dashboards_version')
    op.drop_index(op.f('ix_dashboards_version_operation_type'), table_name='dashboards_version')
    op.drop_index(op.f('ix_dashboards_version_end_transaction_id'), table_name='dashboards_version')
    op.drop_table('dashboards_version')
    op.drop_index(op.f('ix_dashboard_slices_version_transaction_id'), table_name='dashboard_slices_version')
    op.drop_index('ix_dashboard_slices_version_pk_validity', table_name='dashboard_slices_version')
    op.drop_index('ix_dashboard_slices_version_pk_transaction_id', table_name='dashboard_slices_version')
    op.drop_index(op.f('ix_dashboard_slices_version_operation_type'), table_name='dashboard_slices_version')
    op.drop_index(op.f('ix_dashboard_slices_version_end_transaction_id'), table_name='dashboard_slices_version')
    op.drop_table('dashboard_slices_version')
    # ### end Alembic commands ###
